Debug: true
CosmoDataSource:
  mysql: 'island'
  redis: 'island'
LevelLorePattern: '(?<=§f섬\s레벨§l\[\s).*(?=\s§f§l]\s증가)'
ManyWorldsDatabase:
  address: '127.0.0.1'
  port: '3306'
  database: 'test'
  username: 'root'
  password: 'password'
DefaultIslandPermissions:
  ENTER: 'NONE'
  WOOD_DOOR: 'INTERN'
  IRON_DOOR: 'MEMBER'
  FENCE_GATE: 'INTERN'
  REDSTONE_INTERACTION: 'MEMBER'
  IGNORE_LOCK: 'INTERN'
  USE_TP: 'OWNER'
  TP_OTHER: 'OWNER'
  SET_JUKE_BOX: 'OWNER'
  BUILD: 'INTERN'
  OPEN_ISLAND_CHEST: 'MEMBER'
  USE_CHEST: 'MEMBER'
  ITEM_PICKUP: 'NONE'
  ITEM_DROP: 'NONE'
DefaultIslandSettings:
  DISPLAY_NAME: ''
  PRIVATE: 'false'
  ALLOW_PVP: 'false'
  ALLOW_SET_HOME: 'true'
  TIME: '7000'
  TIME_FIX: 'false'
  SUNNY: 'true'
  ENTER_MESSAGE: ''
  EXIT_MESSAGE: ''
  JUKE_BOX: ''
  BUILDERS_UTILITY: 'false'
  MAX_INTERNS: '5'
  MAX_MEMBERS: '5'
  MAX_WARPS: '5'
DefaultWorldBorder:
  weight: 50
  length: 50
UpdateUpgradeSettings: false
DefaultUpgradeSettings:
  MAX_INTERNS:
    1:
      value: 6
      cost: 10
    2:
      value: 7
      cost: 100
    3:
      value: 8
      cost: 1000
    4:
      value: 9
      cost: 10000
    5:
      value: 10
      cost: 100000
  MAX_PLAYERS:
    1:
      value: 6
      cost: 10
    2:
      value: 7
      cost: 100
    3:
      value: 8
      cost: 1000
    4:
      value: 9
      cost: 10000
    5:
      value: 10
      cost: 100000
  BORDER_SIZE:
    1:
      value: 100
      cost: 10
    2:
      value: 200
      cost: 100
    3:
      value: 300
      cost: 1000
    4:
      value: 400
      cost: 10000
    5:
      value: 500
      cost: 100000
  INVENTORY_SIZE:
    1:
      value: 2
      cost: 10
    2:
      value: 3
      cost: 100
    3:
      value: 4
      cost: 1000
    4:
      value: 5
      cost: 10000
    5:
      value: 6
      cost: 100000