main: kr.cosmoislands.cosmoislands.bukkit.CosmoIslandsBukkit
name: CosmoIslands
version: 1.0.0-SNAPSHOT
author: arkarang
api-version: 1.16
depend:
  - CosmoChat
  - HelloBukkit
  - HelloPlayers
  - ManyWorlds
  - CosmoTeleport
  - CosmoDataSource
  - Vault