default:
  initial_island_size: 50
  fallback:
    server: lobby
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0
    pitch: 0
  spawn_location:
    x: 0.5
    y: 64
    z: 0.5
    yaw: 0
    pitch: 0
  reinforce_max_level:
    chest: 5
    size: 6
    interns: 6
    members: 6
  reinforce:
    chest:
      0:
        head: '12345'
        value: 0
        cost: 0
      1:
        head: '12345'
        value: 1
        cost: 1
      2:
        head: '12345'
        value: 2
        cost: 10
      3:
        head: '12345'
        value: 3
        cost: 1000
      4:
        head: '12345'
        value: 4
        cost: 10000
      5:
        head: '12345'
        value: 5
        cost: 100000
      6:
        head: '12345'
        value: 999999
        cost: 100000
    members:
      0:
        head: '12345'
        value: 5
        cost: 0
      1:
        head: '12345'
        value: 6
        cost: 1
      2:
        head: '12345'
        value: 7
        cost: 10
      3:
        head: '12345'
        value: 8
        cost: 1000
      4:
        head: '12345'
        value: 9
        cost: 10000
      5:
        head: '12345'
        value: 10
        cost: 100000
      6:
        head: '12345'
        value: 999999
        cost: 100000
    interns:
      0:
        head: '12345'
        value: 5
        cost: 0
      1:
        head: '12345'
        value: 6
        cost: 1
      2:
        head: '12345'
        value: 7
        cost: 10
      3:
        head: '12345'
        value: 8
        cost: 1000
      4:
        head: '12345'
        value: 9
        cost: 10000
      5:
        head: '12345'
        value: 10
        cost: 100000
      6:
        head: '12345'
        value: 999999
        cost: 100000
    size:
      0:
        head: '12345'
        value: 50
        cost: 0
      1:
        head: '12345'
        value: 100
        cost: 1
      2:
        head: '12345'
        value: 200
        cost: 10
      3:
        head: '12345'
        value: 300
        cost: 1000
      4:
        head: '12345'
        value: 400
        cost: 10000
      5:
        head: '12345'
        value: 500
        cost: 100000
      6:
        head: '12345'
        value: 999999
        cost: 1
  rewards:
    level:
      1: 100
      2: 1000
      3: 2000
      4: 3000
      5: 4000
      6: 5000
      7: 10000
  settings:
    PRIVATE: false
    ALLOW_PVP: false
    ALLOW_SET_WARP: false
    TIME: -1
    TIME_FIX: false
    WEATHER: sunny
    BUILDERS_UTILITY: false
  permissions:
    WOOD_DOOR: 0
    IRON_DOOR: 1
    FENCE_GATE: 1
    REDSTONE_INTERACTION: 1
    USE_TP: 2
    TP_OTHER: 3
    SET_JUKE_BOX: 4
    BUILD: 1
    OPEN_ISLAND_CHEST: 2
    USE_CHEST: 1
    ITEM_PICKUP: 1
    ITEM_DROP: 1

